import { Barlow_Semi_Condensed } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import Footer from "./components/Footer";

const barlowSemi = Barlow_Semi_Condensed({
  weight: ["100", "200", "300", "400", "500", "700"], // Provide an array of weights to load
  variable: "--font-barlow-semi-condensed",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${barlowSemi.variable} antialiased`}>
        {children}
        <Footer />
      </body>
    </html>
  );
}

